// <auto-generated />
using System;
using DAL.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20231202095812_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GraGracz", b =>
                {
                    b.Property<int>("GraczeId")
                        .HasColumnType("int");

                    b.Property<int>("GryId")
                        .HasColumnType("int");

                    b.HasKey("GraczeId", "GryId");

                    b.HasIndex("GryId");

                    b.ToTable("GraGracz");
                });

            modelBuilder.Entity("Model.DataModels.Gra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("RokWydania")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tytul")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WydawnictwoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WydawnictwoId");

                    b.ToTable("Gry");
                });

            modelBuilder.Entity("Model.DataModels.Gracz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataUrodzenia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Narodowosc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nick")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gracze");
                });

            modelBuilder.Entity("Model.DataModels.Wydawnictwo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Siedziba")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Wydawnictwa");
                });

            modelBuilder.Entity("GraGracz", b =>
                {
                    b.HasOne("Model.DataModels.Gracz", null)
                        .WithMany()
                        .HasForeignKey("GraczeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.DataModels.Gra", null)
                        .WithMany()
                        .HasForeignKey("GryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.DataModels.Gra", b =>
                {
                    b.HasOne("Model.DataModels.Wydawnictwo", "Wydawnictwo")
                        .WithMany("Gry")
                        .HasForeignKey("WydawnictwoId");

                    b.Navigation("Wydawnictwo");
                });

            modelBuilder.Entity("Model.DataModels.Wydawnictwo", b =>
                {
                    b.Navigation("Gry");
                });
#pragma warning restore 612, 618
        }
    }
}
